# Generated by Django 3.2.7 on 2021-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('Web design and development', 'Web design and development'), ('Android application development', 'Android application development'), ('Desktop application development', 'Desktop application development'), ('CCTV installation/Network solutions', 'CCTV installation/Network solutions'), ('Computer repair and maintenance', 'Computer repair and maintenance')], max_length=50, null=True)),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Ethiopia', 'Ethiopia'), ('Sudan', 'Sudan'), ('Somalia', 'Somalia'), ('South Sudan', 'South Sudan'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi'), ('Djibouti', 'Djibouti')], max_length=15, null=True)),
                ('how', models.CharField(choices=[('Social media', 'Social media'), ('Friends/Colleague', 'Friends/Colleague'), ('Web search', 'Web search')], max_length=20, null=True)),
                ('message', models.TextField(max_length=300, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
