# Generated by Django 3.2.7 on 2021-09-20 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gikpad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 11, 39, 19, 448445, tzinfo=utc)),
        ),
    ]
