# Generated by Django 3.2.7 on 2021-09-20 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gikpad', '0002_alter_clientrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 11, 57, 44, 50389, tzinfo=utc)),
        ),
    ]
