# Generated by Django 3.2.7 on 2022-01-15 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gikpad', '0003_alter_clientrequest_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientrequest',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 14, 44, 59, 69995, tzinfo=utc)),
        ),
    ]
