# Generated by Django 3.2.7 on 2022-01-16 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gikpad', '0005_auto_20220116_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='gallery',
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 18, 44, 45, 412790, tzinfo=utc)),
        ),
    ]
